cmake_minimum_required(VERSION 3.10)
project(kave VERSION 0.1.0 LANGUAGES C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra -Wpedantic -Werror -std=c11 -D_GNU_SOURCE")
set(CMAKE_BUILD_TYPE Release CACHE STRING "Build type" FORCE)
include_directories(include)
file(GLOB_RECURSE SOURCES src/*.c)
add_executable(kave-server ${SOURCES})
target_link_libraries(kave-server pthread rt)
